final List<String> trendings = [
  'images/m1.jpg',
  'images/m2.jpeg',
  'images/m3.jpeg',
  'images/m1.jpg',
  'images/m2.jpeg',
  'images/m3.jpeg',
];

final List<String> persons = [
  'images/person1.jpg',
  'images/person2.jpg',
  'images/person3.jpg',
  'images/person1.jpg',
  'images/person2.jpg',
  'images/person3.jpg',
  'images/person1.jpg',
  'images/person2.jpg',
  'images/person3.jpg',
  'images/person1.jpg',
  'images/person2.jpg',
  'images/person3.jpg',
];
final List<String> others = [
  'images/m1.jpg',
  'images/m2.jpeg',
  'images/m3.jpeg',
  'images/m1.jpg',
  'images/m2.jpeg',
  'images/m3.jpeg',
  'images/m1.jpg',
  'images/m2.jpeg',
  'images/m3.jpeg',
  'images/m1.jpg',
  'images/m2.jpeg',
  'images/m3.jpeg',
  'images/m1.jpg',
  'images/m2.jpeg',
  'images/m3.jpeg',
];
final List<String> name = [
  'Jordan',
  'Oliver',
  'James Wan',
  'Jordan',
  'Oliver',
  'James Wan',
  'Jordan',
  'Oliver',
  'James Wan',
  'Jordan',
  'Oliver',
  'James Wan',
  'Jordan',
  'Oliver',
  'James Wan'
];
final List<String> noOfScripts = [
  '236 scripts',
  '320 scripts',
  '450 scripts',
  '236 scripts',
  '320 scripts',
  '450 scripts',
  '236 scripts',
  '320 scripts',
  '450 scripts',
  '236 scripts',
  '320 scripts',
  '450 scripts',
  '236 scripts',
  '320 scripts',
  '450 scripts',
];
final List<String> scripts = [
  'Here is the script for loreum ipsum the outstanding script..',
  'Here is the script for loreum ipsum the outstanding script ',
  'Here is the script for loreum ipsum the outstanding script',
  'Here is the script for loreum ipsum the outstanding script',
  'Here is the script for loreum ipsum the outstanding script ',
  'Here is the script for loreum ipsum the outstanding script',
  'Here is the script for loreum ipsum the outstanding script',
];
